# Generated by Django 3.1.6 on 2021-02-18 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.FileField(null=True, upload_to='upload/categoria/')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('presentacion', models.TextField(max_length=100)),
                ('marca', models.CharField(max_length=30)),
                ('fabricante', models.CharField(max_length=30)),
                ('foto', models.FileField(null=True, upload_to='upload/productos/')),
                ('venta_al_granel', models.BooleanField(default=False)),
                ('descripcion', models.TextField(max_length=100)),
                ('nivel_azucar', models.CharField(max_length=10)),
                ('nivel_sal', models.CharField(max_length=30)),
                ('nivel_grasa', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ciudad', models.CharField(max_length=30)),
                ('logo', models.FileField(null=True, upload_to='upload/tienda/')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=100)),
                ('icono', models.FileField(null=True, upload_to='upload/subcategoria/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_En_Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tienda', models.CharField(default=None, max_length=30, null=True)),
                ('id_producto', models.CharField(default=None, max_length=30, null=True)),
                ('sku', models.CharField(default=None, max_length=30, null=True)),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiene_iva', models.BooleanField()),
                ('estado', models.CharField(max_length=30)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
        ),
    ]
