# Generated by Django 3.1.6 on 2021-02-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='id_ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
