# Generated by Django 3.1.6 on 2021-02-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210218_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_en_tienda',
            old_name='id_categoria',
            new_name='categoria',
        ),
    ]
